name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jtsilva26/liatrio-apprenticeship-exercise:index
   
    - name: Run the Docker image
      run: docker run --rm -d --init -p 80:80 jtsilva26/liatrio-apprenticeship-exercise:index
      
    - name: Run tests
      uses: liatrio/github-actions/apprentice-action@master
      
    - name: Login for Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push
      run: docker push jtsilva26/liatrio-apprenticeship-exercise:index
